### ISSUE TITLE
Problem install on Raspberry Pi OS (64-bit) debian 12 bookworm

### ISSUE THREAD

**Issue by botho** [homebridge/homebridge-apt-pkg#11]
### Analysis

When running "sudo apt-get install homebridge" here is the output error 

Preparing to unpack .../homebridge_1.0.34_arm64.deb ...
Running pre-install steps...
Unpacking may take several minutes on low powered devices.
Unpacking homebridge (1.0.34) ...
Setting up homebridge (1.0.34) ...
Running post-install steps...
Adding system user `homebridge' (UID 112) ...
Adding new group `homebridge' (GID 122) ...
Adding new user `homebridge' (UID 112) with group `homebridge' ...
**Not creating `/nonexistent'.
cp: cannot create regular file '/home/homebridge/.bashrc': No such file or directory
chown: cannot access '/home/homebridge/.bashrc': No such file or directory**
Starting Homebridge service....

Homebridge Installation Complete!
You can access the Homebridge UI via:

* http://192.168.1.11:8581

Thanks for installing Homebridge!

ℹ Updating Node.js from v18.16.0 to v18.18.1...
ℹ Target: /opt/homebridge
✔ Download complete.
✔ Cleaned up npm at at /opt/homebridge/lib/node_modules/npm
✔ Installed Node.js v18.18.1
⚠ Please restart Homebridge for the changes to take effect.

### Expected Behavior

expected no error

### Steps To Reproduce

sudo apt-get install homebridge

### Logs

```markdown
When running "sudo apt-get install homebridge" here is the output error 

Preparing to unpack .../homebridge_1.0.34_arm64.deb ...
Running pre-install steps...
Unpacking may take several minutes on low powered devices.
Unpacking homebridge (1.0.34) ...
Setting up homebridge (1.0.34) ...
Running post-install steps...
Adding system user `homebridge' (UID 112) ...
Adding new group `homebridge' (GID 122) ...
Adding new user `homebridge' (UID 112) with group `homebridge' ...
**Not creating `/nonexistent'.
cp: cannot create regular file '/home/homebridge/.bashrc': No such file or directory
chown: cannot access '/home/homebridge/.bashrc': No such file or directory**
Starting Homebridge service....

Homebridge Installation Complete!
You can access the Homebridge UI via:

* http://192.168.1.11:8581

Thanks for installing Homebridge!

ℹ Updating Node.js from v18.16.0 to v18.18.1...
ℹ Target: /opt/homebridge
✔ Download complete.
✔ Cleaned up npm at at /opt/homebridge/lib/node_modules/npm
✔ Installed Node.js v18.18.1
⚠ Please restart Homebridge for the changes to take effect.
```

### Configuration

```json
fresh install
```

### Environment

- OS: Raspberry Pi OS (64-bit) debian 12 bookworm
- Software:
- Node: 
- npm:

### Process Supervisor

hb-service

### Additional Context

When installing plugin, I have another error about directory "nonexistent"

$ hb-service add homebridge-tydom
ℹ CMD: npm --prefix "/var/lib/homebridge" add homebridge-tydom@latest
npm ERR! code EACCES
npm ERR! syscall mkdir
npm ERR! path /nonexistent
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, mkdir '/nonexistent'
npm ERR!  [Error: EACCES: permission denied, mkdir '/nonexistent'] {
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'mkdir',
npm ERR!   path: '/nonexistent'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! Log files were not written due to an error writing to the directory: /nonexistent/.npm/_logs
npm ERR! You can rerun the command with `--loglevel=verbose` to see the logs in your terminal
✖ Plugin installation failed.

workaround : add homebridge user by yourself before installation

**Comment by txhtxh11** [comment]
waiting

**Comment by botho** [comment]
workaround : add homebridge user by yourself before installation

**Comment by SSkull995** [comment]
Hi Botho,
I have the same issue, plus if I try to update the gui-x plugin I always get an error access. No permissions granted. How did you manage? 
Thank you.

**Comment by botho** [comment]
> Hi Botho, I have the same issue, plus if I try to update the gui-x plugin I always get an error access. No permissions granted. How did you manage? Thank you.

Do a complete uninstallation and delete homebridge user:
```
sudo apt-get remove homebridge
sudo rm -rf /etc/apt/sources.list.d/homebridge.list
sudo apt-get purge homebridge
sudo deluser -remove-home homebridge
```

Installtion:
```
sudo adduser --system --group homebridge --home /home/homebridge
curl -sSfL https://repo.homebridge.io/KEY.gpg | sudo gpg --dearmor | sudo tee /usr/share/keyrings/homebridge.gpg  > /dev/null
echo "deb [signed-by=/usr/share/keyrings/homebridge.gpg] https://repo.homebridge.io stable main" | sudo tee /etc/apt/sources.list.d/homebridge.list > /dev/null
sudo apt-get update && sudo apt-get install homebridge
sudo hb-service update-node 
```

**Comment by txhtxh11** [comment]
Hello!
       Very thank you!

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2023年10月16日 14:44
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [homebridge/homebridge] Problem on Raspberry Pi OS (64-bit) debian 12 bookworm (Issue homebridge/homebridge-apt-pkg#11)


Hi Botho, I have the same issue, plus if I try to update the gui-x plugin I always get an error access. No permissions granted. How did you manage? Thank you.

Do a complete uninstallation and delete homebridge user:

sudo apt-get remove homebridge

sudo rm -rf /etc/apt/sources.list.d/homebridge.list

sudo apt-get purge homebridge

sudo deluser -remove-home homebridge

Installtion:

sudo adduser homebridge

curl -sSfL https://repo.homebridge.io/KEY.gpg | sudo gpg --dearmor | sudo tee /usr/share/keyrings/homebridge.gpg  > /dev/null

echo "deb [signed-by=/usr/share/keyrings/homebridge.gpg] https://repo.homebridge.io stable main" | sudo tee /etc/apt/sources.list.d/homebr>

sudo apt-get update && sudo apt-get install homebridge

sudo hb-service update-node

―

**Comment by NorthernMan54** [comment]
This issue is creatable with bookwork 64 gb lite

**Comment by NorthernMan54** [comment]
The adduser command appears to have changed with bookworm and now does this

```
Add a system user
       If called with one non-option argument and the --system option, adduser will add a dynamically allocated system user,  often  abbreviated
       as system user in the context of the adduser package.

       adduser  will  choose the first available UID from the range specified by FIRST_SYSTEM_UID and LAST_SYSTEM_UID in the configuration file.
       This can be overridden with the --uid option.

       By default, system users are placed in the nogroup group.  To place the new system user in an already existing group, use  the  --gid  or
       --ingroup options.  If the --group is given and the identically named group does not already exist, it is created with the same ID.

       If  no  home directory is specified, the default home directory for a new system user is /nonexistent.  This directory should never exist
       on any Debian system, and adduser will never create it automatically.

       Unless a shell is explicitly set with the --shell option, the new system user will have the  shell  set  to  /usr/sbin/nologin.   adduser
       --system does not set a password for the new account.  Skeletal configuration files are not copied.

       Other options will behave as for the creation of a normal user.  The files referenced by UID_POOL and GID_POOL do also work.
```

**Comment by txhtxh11** [comment]
Hi
   Very thank you!OK!

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: Northern ***@***.***>
发送时间: 2023年10月17日 21:47
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [homebridge/homebridge-apt-pkg] Problem install on Raspberry Pi OS (64-bit) debian 12 bookworm (Issue #11)


The adduser command appears to have changed with bookworm and now does this

Add a system user

       If called with one non-option argument and the --system option, adduser will add a dynamically allocated system user,  often  abbreviated

       as system user in the context of the adduser package.



       adduser  will  choose the first available UID from the range specified by FIRST_SYSTEM_UID and LAST_SYSTEM_UID in the configuration file.

       This can be overridden with the --uid option.



       By default, system users are placed in the nogroup group.  To place the new system user in an already existing group, use  the  --gid  or

       --ingroup options.  If the --group is given and the identically named group does not already exist, it is created with the same ID.



       If  no  home directory is specified, the default home directory for a new system user is /nonexistent.  This directory should never exist

       on any Debian system, and adduser will never create it automatically.



       Unless a shell is explicitly set with the --shell option, the new system user will have the  shell  set  to  /usr/sbin/nologin.   adduser

       --system does not set a password for the new account.  Skeletal configuration files are not copied.



       Other options will behave as for the creation of a normal user.  The files referenced by UID_POOL and GID_POOL do also work.

―

**Comment by NorthernMan54** [comment]
The homebridge Debian package has been updated to resolve this issue going forward.
