### ISSUE TITLE
apt full-upgrade - downgrading homebridge?

### ISSUE THREAD

**Issue by mkz212** [homebridge/homebridge-apt-pkg#13]
### Raspberry Pi Model

Raspberry Pi 4 B

### Describe The Bug

When I run `sudo apt full-upgrade` (from ssh) it will update all components but downgrade Homebridge to 1.6.1, also downgrade Homebridge Config Ui and also downgrade node from 20 to 18. Why?

The second issue is the fact that you cannot run this command in Homebridge Terminal if Homebridge appears in the update list. 

Mayby exclude Homebridge from the apt full-upgrade command? So that full-upgrade command can be run directly in Homebridge Terminal? And so that it does not cause downgrade?

**Comment by NorthernMan54** [comment]
@mkz212 I'm not aware of how we could control what a apt full-upgrade does, as it just pulls the latest from the deb repo and installs.

But with that said, I'm currently publishing version 1.1.1 which contains these versions

| Package | Version |
|:-------:|:-------:|
|NodeJS| v18.18.2 |
|Homebridge-Config-UI-X| 4.52.1 |
|Homebridge| 1.7.0 |

We made the strategic decision not to update the bundled NodeJS version from 18.x to NodeJS 20.x to avoid breaking peoples  setups.  We are going to include within the UI, indicators that your OS is out of date and needs updating for future upgrades.  We are likely to make the jump next spring.

**Comment by mkz212** [comment]
Thanks for the information. Next version of Config UI (4.52.2) contain a lot of changes - should come out soon.
