### ISSUE TITLE
V 1.1.1 and 1.1.2 is downgrading Node from V20 to V18

### ISSUE THREAD

**Issue by jostrasser** [homebridge/homebridge-apt-pkg#15]
### Raspberry Pi Model

Raspberry Pi 4 B

### Describe The Bug

While updating the apt package the installer downgrades Node from V20.9.0 to V18.18.2 

It’s better to verify the version and avoid already upgraded Node installations. 

### Logs

Updated to the latest release with Node 20.9.0 installed. After the update, homebridge started with 18.18.2:

```text
^[[37m[11/11/2023, 19:17:55]^[[0m ^[[36m[HB Supervisor]^[[0m OS: Linux 6.1.21-v8+ arm64
^[[37m[11/11/2023, 19:17:55]^[[0m ^[[36m[HB Supervisor]^[[0m Node.js v18.18.2 /opt/homebridge/bin/node
```

I ran `hb-service update-node` after the apt update and got an error, but it was updated to 20.09.0 again.
Cannot attach the log from the update-node command, I think this command will not be logged in a logfile.
Should be easy to reproduce.

**Comment by NorthernMan54** [comment]
The downgrade of NodeJS to 18 is expected as we aren't going to update the NodeJS within the package for a few months.  As anyone with an older OS install will get an error.  So we added to the UI a warning with the config-UI release for people with older installs.

![image](https://github.com/homebridge/homebridge-apt-pkg/assets/19808920/08d1f56d-8a3c-4756-9f49-f432969fed02)

Hopefully people will upgrade ( including myself ), then we can update NodeJS.

**Comment by jostrasser** [comment]
Hi @NorthernMan54 

I understand, thank you!

So I think for me the best way to go is to update the apt package and afterwards back to V20 until the apt is delivering V20 as default version.
Some plugins like Homebridge-hue are already recommending V20 and if possible I want to stay on V20.

After doing it all looks fine so far and if I run the update-node again, all looks fine:
`ℹ Node.js v20.9.0 already up-to-date.`

![image](https://github.com/homebridge/homebridge-apt-pkg/assets/14274103/1e641025-1a4c-4f97-ab20-25a35f2c79f5)

Thanks for your help! :)

BR/JO!
