### ISSUE TITLE
APT Repository node.js version overwrites later installed node.js version

### ISSUE THREAD

**Issue by andrewk123** [homebridge/homebridge-apt-pkg#19]
### Analysis

Updating Homebridge using sudo apt update/upgrade results in current node.js version being overwritten by a =n earlier version.

### Expected Behavior

Upgrades via apt should not overwrite later already installed node.js versions.

### Steps To Reproduce

- Homebridge installed on a Pi4 (Debian GNU/Linux Bullseye (11)).
- Homebridge was installed using the "sudo apt install homebridge" method currently prescribed for a Pi.
- Homebridge was at version v1.7.0 and node.js was at v20.10.0 (node.js upgraded from v18 using hb-service update-node when the UI prompted that an upgrade was available).
- Ran sudo apt update/sudo apt upgrade on the Pi4 resulting in the following apt message: "Unpacking homebridge (1.1.4) over (1.1.3) ..."
- After Homebridge service reloads node.js version has downgraded to 18.18.2 and the UI is again prompting to upgrade node.js
- Ran hb-service update-node again, node.js updated back to v20.10.0

### Logs

```markdown
None generated
```

### Configuration

```json
Not applicable
```

### Environment

- OS: Debian GNU/Linux Bullseye (11) (ie Raspberry Pi OS)
- Software: 1.7.0
- Node: 20.10.0
- npm: 10.2.3

### Process Supervisor

hb-service

**Comment by NorthernMan54** [comment]
This is the expected behaviour, as the apt package is currently using NodeJS 18.x

**Comment by andrewk123** [comment]
Could I make the suggestion that it might make sense to co-ordinate the versions used by the APT package and the upgrade recommendations from the UI?

**Comment by NorthernMan54** [comment]
@andrewk123 we publish these with a delay from the core packages to ensure that the release is very stable, and not cause issues for users etc.  Hence them always being a little bit behind.

In regards to NodeJS, the continued usage of NodeJS 18, is deliberate to allow people time to update their OS installations to support NodeJS 20.  ( We had introduced indicators to show that the OS is outdated and needs updating in the fall, to prompt people to update, prior to forcing the update to people ).  In a few weeks we will make the jump to NodeJS 20.
