### ISSUE TITLE
Repo updates brings back node 18 from node 20

### ISSUE THREAD

**Issue by roboterm** [homebridge/homebridge-apt-pkg#23]
### Analysis

When upgrading from 1.1.5 to 1.1.6 my node was set back to 18.

### Expected Behavior

Repo updates shouldn't affect node version.

### Steps To Reproduce

run sude apt-get update;sudo apt-get upgrade --y via ssh

### Logs

```markdown
sorry
```

### Configuration

```json
nothing
```

### Environment

- OS: Debian GNU/Linux 12 (bookworm)
- Software: homebridge repo plugin 1.1.5
- Node: 20.10
- npm: 9.2.0

### Process Supervisor

hb-service

**Comment by donavanbecker** [comment]
See https://github.com/homebridge/homebridge-apt-pkg/issues/19#issuecomment-1837520229

**Comment by roboterm** [comment]
> See [#19 (comment)](https://github.com/homebridge/homebridge-apt-pkg/issues/19#issuecomment-1837520229)

Thank you @donavanbecker
