### ISSUE TITLE
Unable to start hb-service after upgrading on RPI from 1.0.30 to 1.0.31

### ISSUE THREAD

**Issue by peck4919** [homebridge/homebridge-apt-pkg#3]
### Analysis

Please see bug report on main Homebridge page linked here: https://github.com/homebridge/homebridge/issues/3259

### Expected Behavior

Homebridge should update and continue to work.

### Steps To Reproduce

On RPi, update from 1.0.30 to 1.0.31 via apt upgrade.

### Logs

```markdown
Starting Homebridge...
homebridge.service: Failed to determine supplementary groups: No such process
homebridge.service: Failed at step GROUP spawning /bin/run-parts: No such process
Started Homebridge.
homebridge.service: Failed to determine supplementary groups: No such process
homebridge.service: Failed at step GROUP spawning /opt/homebridge/start.sh: No such process
homebridge.service: Main process exited, code=exited, status=216/GROUP
homebridge.service: Failed with result 'exit-code'.
homebridge.service: Scheduled restart job, restart counter is at 12.
Stopped Homebridge.
```

### Configuration

```json
N/A
```

### Environment

- OS: Ubuntu 22.04
- Node:v18.12.1

### Process Supervisor

hb-service

### Additional Context

https://github.com/homebridge/homebridge/issues/3259

**Comment by DrDeath** [comment]
The issue itself could be in:
https://github.com/homebridge/homebridge-apt-pkg/commit/95baa57589510a2babe4512bdb3ba25c8249e93b

/lib/systemd/system/homebridge.service

The SupplementaryGroups  "homebridge" does not exist on my "old" homebridge installation.
Therefore the user "homebridge" does not belong to the not existing group "homebridge".

If I comment out the line:

`SupplementaryGroups=homebridge`

in `/lib/systemd/system/homebridge.service`

and do a 

`sudo systemctl daemon-reload`
`sudo systemctl restart homebridge`

the service starts again:

```
systemctl status homebridge
● homebridge.service - Homebridge
     Loaded: loaded (/lib/systemd/system/homebridge.service; enabled; vendor preset: enabled)
     Active: active (running) since Fri 2022-11-11 15:19:36 CET; 5s ago
    Process: 18862 ExecStartPre=/bin/run-parts /etc/hb-service/homebridge/prestart.d (code=exited, status=0/SUCCESS)
   Main PID: 18865 (hb-service)
      Tasks: 11 (limit: 4163)
        CPU: 6.557s
     CGroup: /system.slice/homebridge.service
             └─18865 hb-service

Nov 11 15:19:35 raspberrypi4 systemd[1]: Starting Homebridge...
Nov 11 15:19:35 raspberrypi4 run-parts[18863]: Ensuring /var/lib/homebridge and /opt/homebridge are owned by homebridge
Nov 11 15:19:36 raspberrypi4 systemd[1]: Started Homebridge.
Nov 11 15:19:37 raspberrypi4 start.sh[18865]: [11.11.2022, 15:19:37] [HB Supervisor] Homebridge Storage Path: /var/lib/homebridge
```

**Comment by elyscape** [comment]
It looks like, for a period of time, the `homebridge` user was created without a matching group. I'll submit a PR to handle those systems.
